networks:
  net_back:
  net_front:

services:
  back:
    container_name: back
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./back/
      dockerfile: ./DockerFile
    ports:
      - "8080:8080"
    networks:
      - net_back
      - net_front