networks:
  net_back:
  net_front:

services:
  front:
    container_name: front
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./front/
      dockerfile: ./Dockerfile
    ports:
      - "${FRONT_PORT}:3000"
    networks:
      - net_front
      - net_back
  back:
    container_name: back
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./back/
      dockerfile: ./Dockerfile
    ports:
      - "${BACK_PORT}:8080"
    networks:
      - net_back
      - net_front
  db:
    container_name: postgres
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - net_back
